.Dd today
.Os Local Scripts
.Dt __CMD__ 1 LOCAL
.Sh NAME
.Nm __CMD__
.Nd A command to setup a local development environment
.Sh SYNOPSIS
.Nm
.Op path Op command \...
.Nm
.Fl -help
.Sh DESCRIPTION
.\" .Sh ENVIRONMENT
.\" .Sh FILES
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" .Sh COMPATIBILITY
.Sh SEE ALSO
.\" .Sh STANDARDS
.\" .Sh HISTORY
.Sh AUTHORS
.An Ihab Hussein Aq ihab@ihabhussein.com
.\" .Sh BUGS
